# Generated by Django 4.2 on 2023-04-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customer_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('customer_unique_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'customers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id_file', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.CharField(blank=True, max_length=50, null=True)),
                ('file_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'files',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Geolocation',
            fields=[
                ('id_geolocation', models.AutoField(primary_key=True, serialize=False)),
                ('geolocation_zip_code_prefix', models.CharField(blank=True, max_length=50, null=True)),
                ('geolocation_lat', models.DecimalField(blank=True, decimal_places=17, max_digits=20, null=True)),
                ('geolocation_lng', models.DecimalField(blank=True, decimal_places=17, max_digits=20, null=True)),
                ('geolocation_city', models.CharField(blank=True, max_length=255, null=True)),
                ('geolocation_state', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'geolocation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GeolocationNorm',
            fields=[
                ('geolocation_zip_code_prefix', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('geolocation_city', models.CharField(blank=True, max_length=50, null=True)),
                ('geolocation_state', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'geolocation_norm',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('order_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('shipping_limit_date', models.DateTimeField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('freight_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('order_item_quantity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'order_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderPlaced',
            fields=[
                ('order_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('order_status', models.CharField(blank=True, max_length=50, null=True)),
                ('order_purchase_timestamp', models.DateTimeField(blank=True, null=True)),
                ('order_approved_at', models.DateTimeField(blank=True, null=True)),
                ('order_delivered_carrier_date', models.DateTimeField(blank=True, null=True)),
                ('order_delivered_customer_date', models.DateTimeField(blank=True, null=True)),
                ('order_estimated_delivery_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'order_placed',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('payments_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('payment_sequential', models.IntegerField(blank=True, null=True)),
                ('payment_type', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_installments', models.IntegerField(blank=True, null=True)),
                ('payment_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'payments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('product_category_name', models.CharField(blank=True, max_length=50, null=True)),
                ('product_height_cm', models.IntegerField(blank=True, null=True)),
                ('product_width_cm', models.IntegerField(blank=True, null=True)),
                ('product_name_lenght', models.IntegerField(blank=True, null=True)),
                ('product_description_lenght', models.IntegerField(blank=True, null=True)),
                ('product_photos_qty', models.IntegerField(blank=True, null=True)),
                ('product_weight_g', models.IntegerField(blank=True, null=True)),
                ('product_length_cm', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('review_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('review_score', models.IntegerField(blank=True, null=True)),
                ('review_comment_title', models.CharField(blank=True, max_length=50, null=True)),
                ('review_comment_message', models.CharField(blank=True, max_length=50, null=True)),
                ('review_creation_date', models.DateTimeField(blank=True, null=True)),
                ('review_answer_timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reviews',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sellers',
            fields=[
                ('seller_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'sellers',
                'managed': False,
            },
        ),
    ]
